### PR TITLE
Add maintainers & update recipe

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR:
* adds the PySAL Steering Council as maintainers
* updates versioning and requirements

### CODE REVIEW

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by jGaboardi** [comment]
@JamesSaxon Would you be able to give this PR a review and merge? After that the PySAL Steering Council will be able to help share the load on maintenance.

**Comment by JamesSaxon** [comment]
Sure, I'll have a look this evening.  Thanks for doing this.

**Comment by jGaboardi** [comment]
> Sure, I'll have a look this evening. Thanks for doing this.

You bet. After this is taken care of, I'll clear out #2 , #8 , and #10

**Review by JamesSaxon — APPROVED** [review]
Thanks @jGaboardi for keeping this up to date.

**Pull request merged**
